kind: Deployment
apiVersion:  apps/v1
metadata:
  namespace: rbac-ns
  name: apache-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache-app

  template:
    metadata:
      name: apache
      labels:
        app: apache-app
    spec:
      containers:
      - name: apache
        image: httpd:latest
        ports:
        - containerPort: 4040
