kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manager
  namespace: rbac-ns

rules:
  - apiGroups: ["", "apps", "rbac.authorization.k8s.io/v1", "batch"]
    resources: ["deployment", "pod", "service"]
    verbs: ["get", "apply", "delete", "watch", "create", "patch"]
